name: Plan

on:
  pull_request:
    branches:
      - main

# cancel workflow runs in progress when a new commit comes through
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:  
  test-account-plan:
    uses: willwebster5/reusable_workflows/.github/workflows/terraform-plan-apply.yml@main
    with:
      environment: test-account
      directory: test-account
      region: us-east-1
      terraform_version: 1.3.9
      tflint_version: v0.45.0
      workspace: aws-security-tf
      dynamo_statelock_table: terraform-state-lock-dynamo
      apply: false
    secrets:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

