name: 'Terraform Apply'

on:
  push:
    branches:
      - main

jobs:
  Test-Account:
    uses: willwebster5/reusable_workflows/.github/workflows/terraform-plan-apply.yml@v0.1.0
    with:
      environment: test-account
      directory: test-account
      region: us-east-1
      terraform_version: 1.3.10
      tflint_version: v0.45.0
      workspace: aws-security-tf
      dynamo_statelock_table: terraform-state-lock-dynamo
      apply: true
    secrets:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}